### ISSUE TITLE
editing bug on Windows 10

### ISSUE THREAD

**Issue by pharaohnof** [infely/mngr#1]
Unable to enter editing mode by pressing either enter or E on Windows 10 using gitbash, powershell or command prompt.....works perfectly on my debian 10 machine and Windows Subsystem for Linux (running Ubuntu)

**Comment by pharaohnof** [comment]
Is it possible to connect to a remote cloud cluster from this program? ie.. a mongodb/cloud/atlas cluster?

**Comment by infely** [comment]
> Unable to enter editing mode by pressing either enter or E on Windows 10 using gitbash, powershell or command prompt.....works perfectly on my debian 10 machine and Windows Subsystem for Linux (running Ubuntu)

Sorry, I have no plans to support editing on Windows, because it doesn't have preinstalled CLI editor
But you can make pull request with your suggestion

> Is it possible to connect to a remote cloud cluster from this program? ie.. a mongodb/cloud/atlas cluster?

Now it's possible by passing -u param with connection url
